[QA-323] Pipe functionality added
maksim-estonia/ipc-task pull request #2
Opened 2022-02-17 12:17 UTC by maksim-estonia

Some remarks:

- I have used open() instead of pipe(). This is as far as I'm aware the same with the difference being that pipe opens a read/write, whereas I have specified every time whether something is meant for reading or writing.

If this turns out to be incorrect I'm willing to change but I don't think it is.

![pipe-open](https://user-images.githubusercontent.com/97879338/154478923-82559851-c8d1-4161-9688-559981e05a22.png)

- Currently when sending a file I'm doing this line-by-line, however to indicate that the file has ended to the receiving side I always add "end" as the last line to the text file. This is not ideal, however I haven't been able to resolve this and have decided to wait and see how others address this problem. 

I've already discussed this issue a bit with Ivan, but basicly it comes down to this:
On the receive side I'm reading in a string, which can only contain chars, so this is for example why '/0' needs to be re-added every time a line gets received. Now EOF is indicated by '/-1' as far as I know, but I can't put this into a string, so it can't be sent and can't be received and compared?

![eof-problem](https://user-images.githubusercontent.com/97879338/154479817-36a5dc8e-870d-43b7-954d-0ad2f46c68b6.png)

2022-02-17 15:23 UTC, ivan-estonia requested changes

2022-02-17 15:23 UTC, ivan-estonia commented on ipc_receivefile/src/ipc_receivefile.c
Arguments could be provided in random order, so it's better to use [getopt_long()](https://www.gnu.org/software/libc/manual/html_node/Getopt-Long-Option-Example.html) for arguments handling.

In current variant the program will faile in case of the following command:
`ipc_receive --file myFile --pipe path`

2022-02-17 15:23 UTC, ivan-estonia commented on ipc_receivefile/src/receive_pipe_processing.c
> +	mknod(FIFO_FILE, S_IFIFO|0640, 0);
As I understand the path to FIFO (pipe) should be provided via --pipe argument.

2022-02-17 15:23 UTC, ivan-estonia commented on ipc_receivefile/src/receive_pipe_processing.c
> +	char readbuf[80];
I suppose, you can use a bigger buffer

2022-02-17 15:23 UTC, ivan-estonia commented on ipc_sendfile/src/send_pipe_processing.c
> +	while (fgets(str, 80, fp) != NULL)
To avoid using a line by line executions, use read() function and buffer with fixed size: e.g. 1024

2022-02-17 15:23 UTC, ivan-estonia commented on ipc_sendfile/src/send_pipe_processing.c
> +	while (fgets(str, 80, fp) != NULL)
When read return 0  it means that file is completely read and you should signalize the receiver, that this is the end. To do this, just use the following:
```
 str[0] = EOF;
 write(fd, str, 1);
```
on the receiver side after each read() check the EOF:
`if (readbuf[read_bytes - 1] == EOF) `

2022-02-17 18:44 UTC, ivan-estonia commented on ipc_sendfile/src/send_pipe_processing.c
> +	while (fgets(str, 80, fp) != NULL)
Already changed this logic. The `EOF` logic doesn't work with the binary files, so it's better to get the size of the file and send it in header. 
Mb there are other solutions.

2022-02-18 11:40 UTC, baovu-unikie commented
Here is the result when running.
![image](https://user-images.githubusercontent.com/97879325/154675485-8f958d26-b0f3-4217-969a-ac6cf555420c.png)

2022-02-22 12:00 UTC, maksim-estonia commented
Everything should work now, @baovu-unikie  could you take another look?

2022-02-22 12:04 UTC, ivan-estonia approved these changes

2022-02-23 06:58 UTC, merged